### ISSUE TITLE
Invalid telegram configuration

### ISSUE THREAD

**Issue by LukeSkyDriver** [Der-Henning/tgtg#110]
Hi 

I was sucessfully able to run the scanner with my bot that was created round 5 years ago and I am unsing for home automation. Here the isssue is that the scanner is giving the error that it is already used in an nother instance what is true.

`2022-06-25 06:20:56 WARNING  You enabled the Telegram notifications without providing a chat id!
2022-06-25 06:20:56 WARNING  Send 6266 to the bot in your desired chat.
2022-06-25 06:20:56 WARNING  Waiting for code ...
Traceback (most recent call last):
  File "scanner.py", line 238, in <module>
  File "scanner.py", line 223, in main
  File "scanner.py", line 73, in __init__
  File "notifiers\__init__.py", line 18, in __init__
  File "notifiers\telegram.py", line 38, in __init__
  File "notifiers\telegram.py", line 109, in _get_chat_id
  File "telegram\ext\extbot.py", line 226, in get_updates
  File "telegram\bot.py", line 133, in decorator
  File "telegram\bot.py", line 3057, in get_updates
  File "telegram\bot.py", line 298, in _post
  File "telegram\utils\request.py", line 361, in post
  File "telegram\utils\request.py", line 283, in _request_wrapper
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
[12580] Failed to execute script 'scanner' due to unhandled exception!`

When enting a chatID I got a sample notification and the scanner runs with the warning about multiple instances of the getUpdate request. Fine

Thats why I created an additional bot in telegram and here I see an issue. When using a new/additional bot the scanner reports an Error saying that the Telegram Configuration is invalid. I verified the token, tired to enable all possible right to the bot. No sucess.

`2022-06-25 06:27:49 INFO     Version 1.10.4
2022-06-25 06:27:49 INFO     ©2021, Henning Merklinger
2022-06-25 06:27:49 INFO     For documentation and support please visit https://github.com/Der-Henning/tgtg
2022-06-25 06:27:49 INFO
2022-06-25 06:27:49 INFO     Loaded config from config.ini
2022-06-25 06:27:51 ERROR    Configuration Error - Invalid Telegram configuration`

I observed that the new bots token is longer than the one of my 5 years old bot.

Please check why this is not working or at least provide some more output for this error if possible to see why the condig is invalid.

Thank you in advance. Luke

**Comment by Der-Henning** [comment]
Hi @LukeSkyDriver.

Yes you cannot / should not use the same bot for multiple services.

The Telegram bot tokens are always in the format `8-10 digits:35 alnum characters plus _-`. E.g. something like this: `123456789:AaZz0...AaZz9`. Can you confirm your token matches this format?
To check your token you can call the telegram API with `curl -s https://api.telegram.org/bot{YOURTOKEN}/getMe`. Thats the same request this scanner is using to check your token. You can also navigate to this url with your browser.
The answer should look something like this:
`{"ok":true,"result":{"id":_____,"is_bot":true,"first_name":"_____","username":"_______","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false}}`

**Comment by LukeSkyDriver** [comment]
Hi Henning

Ok. Now after ten times checking and changing the token characters it worked after hard copy and paste the token. I might be stupid in entering the correct token or I don`t know. Now it is working fine. The curl link is worth adding to the FAQ :D

Thnak you. Best regards. Luke
