### ISSUE TITLE
Special characters and emojis break config on Windows

### ISSUE THREAD

**Issue by hauk92** [Der-Henning/tgtg#274]
Having special characters in the custom telegram message body mangles the characters or throws an error. Two examples:

`body = Sonderzeichen "ä"`
turns into
`body = Sonderzeichen "ÃƒÂ¤"`
after running the scanner once and gets mangled further on every consecutive run.

`body = ⏰`
throws an exception
```
2023-02-13 00:32:00 INFO     Sending test Notifications ...
Traceback (most recent call last):
  File "main.py", line 279, in <module>
  File "main.py", line 170, in main
  File "main.py", line 189, in _run_scanner
  File "scanner.py", line 143, in run
  File "models\config.py", line 443, in save_tokens
  File "configparser.py", line 698, in read
  File "configparser.py", line 1021, in _read
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1106: character maps to <undefined>
[19804] Failed to execute script 'main' due to unhandled exception!
```
This only happens if the scanner writes something to the config file to update the tgtg tokens and not if i get locked out by a captcha and no tokens are updated.

**Comment by Der-Henning** [comment]
Hi @hauk92.
Thank you for your bug report.
The issue should be fixed with commit a7ee1579469cbcd48b12567e5970c4577dfd262e and will be part of the next release.

**Comment by Der-Henning** [comment]
The fix is part of this [pre-Release](https://github.com/Der-Henning/tgtg/suites/10938474658/artifacts/553356097) build.
Any feedback is appreciated! :)

**Comment by hauk92** [comment]
Works great, thank you!
