### ISSUE TITLE
Cron error `invalid literal for int() with base 10: '*"'`

### ISSUE THREAD

**Issue by vwkd** [Der-Henning/tgtg#391]
Using `SCHEDULE_CRON` I get the error `ValueError: invalid literal for int() with base 10: '*"'`. The error also seems to crash the entire app.

`docker-compose.yml`

```yml
services:
    tgtg:
      image: derhenning/tgtg:latest
      environment:
        - SCHEDULE_CRON="* 6-20 * * *"
      ...
```

docker logs

```
2023-07-19T09:57:50.166608776Z 2023-07-19 11:57:50 INFO     Scanner started ...
2023-07-19T09:57:50.168053537Z Traceback (most recent call last):
2023-07-19T09:57:50.168074537Z   File "/home/tgtg/.local/lib/python3.10/site-packages/cron_descriptor/ExpressionDescriptor.py", line 120, in get_full_description
2023-07-19T09:57:50.168299917Z     day_of_week_desc = self.get_day_of_week_description()
2023-07-19T09:57:50.168317908Z   File "/home/tgtg/.local/lib/python3.10/site-packages/cron_descriptor/ExpressionDescriptor.py", line 330, in get_day_of_week_description
2023-07-19T09:57:50.168552338Z     return self.get_segment_description(
2023-07-19T09:57:50.168568558Z   File "/home/tgtg/.local/lib/python3.10/site-packages/cron_descriptor/ExpressionDescriptor.py", line 455, in get_segment_description
2023-07-19T09:57:50.168806788Z     description = get_description_format(expression).format(get_single_item_description(expression))
2023-07-19T09:57:50.168820718Z   File "/home/tgtg/.local/lib/python3.10/site-packages/cron_descriptor/ExpressionDescriptor.py", line 333, in <lambda>
2023-07-19T09:57:50.169023618Z     lambda s: get_day_name(s),
2023-07-19T09:57:50.169033178Z   File "/home/tgtg/.local/lib/python3.10/site-packages/cron_descriptor/ExpressionDescriptor.py", line 303, in get_day_name
2023-07-19T09:57:50.169177149Z     return ExpressionDescriptor.number_to_day(int(exp))
2023-07-19T09:57:50.169201989Z ValueError: invalid literal for int() with base 10: '*"'
2023-07-19T09:57:50.169207859Z 
2023-07-19T09:57:50.169211599Z During handling of the above exception, another exception occurred:
2023-07-19T09:57:50.169215939Z 
2023-07-19T09:57:50.169219319Z Traceback (most recent call last):
2023-07-19T09:57:50.169250019Z   File "/app/main.py", line 339, in <module>
2023-07-19T09:57:50.169375329Z     main()
2023-07-19T09:57:50.169384519Z   File "/app/main.py", line 220, in main
2023-07-19T09:57:50.169487499Z     _run_scanner(scanner)
2023-07-19T09:57:50.169495799Z   File "/app/main.py", line 248, in _run_scanner
2023-07-19T09:57:50.169608229Z     scanner.run()
2023-07-19T09:57:50.169620249Z   File "/app/scanner.py", line 199, in run
2023-07-19T09:57:50.169736919Z     self.cron.get_description(self.config.locale))
2023-07-19T09:57:50.169746179Z   File "/app/models/cron.py", line 39, in get_description
2023-07-19T09:57:50.169807159Z     return "; ".join(get_description(cron, options=self.options)
2023-07-19T09:57:50.169838159Z   File "/app/models/cron.py", line 39, in <genexpr>
2023-07-19T09:57:50.169900569Z     return "; ".join(get_description(cron, options=self.options)
2023-07-19T09:57:50.169907919Z   File "/home/tgtg/.local/lib/python3.10/site-packages/cron_descriptor/ExpressionDescriptor.py", line 652, in get_description
2023-07-19T09:57:50.170088970Z     return descripter.get_description(DescriptionTypeEnum.FULL)
2023-07-19T09:57:50.170098450Z   File "/home/tgtg/.local/lib/python3.10/site-packages/cron_descriptor/ExpressionDescriptor.py", line 104, in get_description
2023-07-19T09:57:50.170182240Z     return choices.get(description_type, self.get_seconds_description)()
2023-07-19T09:57:50.170191620Z   File "/home/tgtg/.local/lib/python3.10/site-packages/cron_descriptor/ExpressionDescriptor.py", line 136, in get_full_description
2023-07-19T09:57:50.170264530Z     raise FormatException(description)
2023-07-19T09:57:50.170271720Z cron_descriptor.Exception.FormatException
```

version

Digest:sha256:1ce515533db6b0425639be017dc576c270ecff8dc8da315ad2ab56771675978e

**Comment by floriegl** [comment]
I assume the issue is that you are using quotation marks around the cron expression. If you check https://github.com/Der-Henning/tgtg/blob/142b32c0f68af981371dbfa34f344c407827e033/docker-compose.yml#L12 you can see that the example doesn't use quotation marks too. Also, the fact that the exception gets raised in "2023-07-19T09:57:50.170182240Z     return choices.get(description_type, self.get_seconds_description)()" implies that it has issues parsing the seconds which would be the first part of the cron expression.

**Comment by vwkd** [comment]
Thanks, removing the quotes fixes it!

Though a bit strange, I assumed YAML would allow optional quotes.
