### ISSUE TITLE
TypeError: Retry.__init__() got an unexpected keyword argument 'allowed_methods

### ISSUE THREAD

**Issue by matkoniecz** [Der-Henning/tgtg#407]
```
python3.10 -m tgtg_scanner
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mateusz/.local/lib/python3.10/site-packages/tgtg_scanner/__main__.py", line 19, in <module>
    from tgtg_scanner.models import Config
  File "/home/mateusz/.local/lib/python3.10/site-packages/tgtg_scanner/models/__init__.py", line 3, in <module>
    from tgtg_scanner.models.favorites import Favorites
  File "/home/mateusz/.local/lib/python3.10/site-packages/tgtg_scanner/models/favorites.py", line 7, in <module>                                                                             
    from tgtg_scanner.tgtg import TgtgClient                                                                                                                                                 
  File "/home/mateusz/.local/lib/python3.10/site-packages/tgtg_scanner/tgtg/__init__.py", line 1, in <module>                                                                                
    from tgtg_scanner.tgtg.tgtg_client import TgtgClient                                                                                                                                     
  File "/home/mateusz/.local/lib/python3.10/site-packages/tgtg_scanner/tgtg/tgtg_client.py", line 48, in <module>                                                                            
    class TgtgSession(requests.Session):                                                                                                                                                     
  File "/home/mateusz/.local/lib/python3.10/site-packages/tgtg_scanner/tgtg/tgtg_client.py", line 50, in TgtgSession                                                                         
    max_retries=Retry(                                                                                                                                                                       
TypeError: Retry.__init__() got an unexpected keyword argument 'allowed_methods
```

**Comment by floriegl** [comment]
You somehow had the urllib3 < 1.26. See https://github.com/psf/requests/issues/5946#issuecomment-926903071 and https://urllib3.readthedocs.io/en/1.25.11/reference/urllib3.util.html and https://urllib3.readthedocs.io/en/1.26.0/reference/urllib3.util.html for the documentation update

**Comment by floriegl** [comment]
@matkoniecz also please update the scanner. Your version is very out of date and some TGTG endpoints changed in the mean time already

**Comment by matkoniecz** [comment]
I think I ended using different API, but if my code will break then I will use updated tgtg version
