### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by iplanwebsites** [Der-Henning/tgtg#507]
Script had been working initially, but now getting error on various IPs.
Tried a fresh setup, but it seems something is broken elsewhere than the program files. Does it save anything elsewhere?

`2024-06-11 23:07:40 INFO     Version 1.21.1
2024-06-11 23:07:40 INFO     ©2024, Henning Merklinger
2024-06-11 23:07:40 INFO     For documentation and support please visit https://github.com/Der-Henning/tgtg/wiki
2024-06-11 23:07:40 INFO
2024-06-11 23:07:41 INFO     Starting login process ...
2024-06-11 23:07:41 WARNING  Failed to get latest APK version!
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "urllib3/connectionpool.py", line 1099, in _validate_conn
  File "urllib3/connection.py", line 653, in connect
  File "urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1104, in _create
  File "ssl.py", line 1382, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 793, in urlopen
  File "urllib3/connectionpool.py", line 491, in _make_request
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 589, in send
  File "urllib3/connectionpool.py", line 877, in urlopen
  File "urllib3/connectionpool.py", line 877, in urlopen
  File "urllib3/connectionpool.py", line 877, in urlopen
  [Previous line repeated 2 more times]
  File "urllib3/connectionpool.py", line 847, in urlopen
  File "urllib3/util/retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='apptoogoodtogo.com', port=443): Max retries exceeded with url: /api/auth/v3/authByEmail (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tgtg_scanner/__main__.py", line 348, in <module>
  File "tgtg_scanner/__main__.py", line 215, in main
  File "tgtg_scanner/__main__.py", line 259, in _run_scanner
  File "tgtg_scanner/scanner.py", line 173, in run
  File "tgtg_scanner/tgtg/tgtg_client.py", line 272, in login
  File "tgtg_scanner/tgtg/tgtg_client.py", line 187, in _post
  File "tgtg_scanner/tgtg/tgtg_client.py", line 96, in post
  File "requests/sessions.py", line 637, in post
  File "requests/sessions.py", line 589, in request
  File "tgtg_scanner/tgtg/tgtg_client.py", line 103, in send
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 620, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='apptoogoodtogo.com', port=443): Max retries exceeded with url: /api/auth/v3/authByEmail (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
[50283] Failed to execute script '__main__' due to unhandled exception!`

**Comment by iplanwebsites** [comment]
@JamesMayB I didn't look further into this issue.
